/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SW02;

import com.mitchtalmadge.asciidata.graph.ASCIIGraph; //Hier erfolgt der Import der Dependency in diese Klasse.

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        String graph = ASCIIGraph.fromSeries(new double[] {1.0,2.0,3.0,10.0,7.0,9.0,5.0,4.0}).plot();  // Hier wird der Graph mit den verschiednen Werten erstellt.
        System.out.println(graph); //Hier wird der Graph in die CLI geprinted
    }
}
